[GENERAL]
title = "Tanks"
ident = "tanks"
exec = "init.py"
python = "bin/python"

[INSTALL]
options.server_host = ""
options.server_port_websocket = 9991
options.server_port_http = 9990
piplibs = [
    'websockets',
    'mysql-connector-python'
]

